spring:
  profiles:
    active: dev
  application:
    name: web-starter
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}