spring:
  datasource:
    url: jdbc:h2:file:~/h2/spring-boot-demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    data-username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: false
  data:
    mongodb:
      host: 127.0.0.1
      database: database
logging:
  level:
    com.github.wenslo: debug
    org.springframework: warn
    com.zaxxer: info
    org.hibernate: warn
    org.mongodb: info
    org.apache: warn
    com.aliyun.openservices: warn
    org.jxls: warn
server:
  servlet:
    session:
      cookie:
        max-age: 30m