spring:
  datasource:
    url: jdbc:h2:file:~/h2/spring-boot-demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    data-username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: database
logging:
  level:
    com.github.wenslo: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    org.springframework: warn
    com.zaxxer: info
    org.hibernate: warn
    org.mongodb: warn
    org.apache: warn
    com.aliyun.openservices: warn